### ISSUE TITLE
brI18n - arquivo de tradução

### ISSUE THREAD

**Issue by carlosantoniodasilva** [tapajos/brazilian-rails#3]
O arquivo de tradução parece estar utilizando a versão anterior no que se refere ao support > array:

```
support:
  array:
    sentence_connector: "e"
    skip_last_comma: true 
```

Para a nova versão do Rails seria algo como:

```
support:
  array:
    words_connector: ', '
    two_words_connector: ' e '
    last_word_connector: ' e '
```

Abraços e parabéns pelo ótimo trabalho.
