### ISSUE TITLE
brdata: Data errada de feriado (Independência)

### ISSUE THREAD

**Issue by maioral** [tapajos/brazilian-rails#47]
A data passada do feriado da independência está errado. O informado é 07/08 e o correto é 07/09.

``` yaml
# brdata/lib/brdata/config/nacionais_fixos.yml

confraternizacao_mundial:
  dia: 01
  mes: 01
tiradentes:
  dia: 21
  mes: 04
trabalho:
  dia: 01
  mes: 05
independencia:
  dia: 07
  mes: 08
republica:
  dia: 15
  mes: 11
natal:
  dia: 25
  mes: 12
```
